/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#bbfd00",
        "on-primary-fixed-variant": "#005e64",
        "secondary-container": "#7000ff",
        "surface-tint": "#8ff5ff",
        "surface-variant": "#222531",
        "surface-dim": "#0c0e16",
        "outline": "#74757f",
        "on-surface-variant": "#aaaab6",
        "on-primary-container": "#005359",
        "background": "#0c0e16",
        "on-secondary-fixed-variant": "#6300e2",
        "surface-container-lowest": "#000000",
        "inverse-primary": "#006a71",
        "inverse-surface": "#faf8ff",
        "primary-fixed": "#00eefc",
        "secondary": "#ac89ff",
        "error": "#ff716c",
        "on-tertiary-container": "#435d00",
        "primary-container": "#00eefc",
        "on-secondary-container": "#f8f1ff",
        "on-tertiary": "#4a6600",
        "primary-fixed-dim": "#00deec",
        "surface-container-low": "#11131c",
        "error-dim": "#d7383b",
        "surface-container-high": "#1d1f2a",
        "tertiary-dim": "#b0ed00",
        "on-tertiary-fixed-variant": "#4b6800",
        "tertiary-container": "#bbfd00",
        "surface": "#0c0e16",
        "on-secondary-fixed": "#41009a",
        "error-container": "#9f0519",
        "on-error": "#490006",
        "on-background": "#ededf9",
        "tertiary": "#e9ffb9",
        "on-primary": "#005d63",
        "primary-dim": "#00deec",
        "surface-container": "#171923",
        "on-surface": "#ededf9",
        "on-error-container": "#ffa8a3",
        "tertiary-fixed-dim": "#b0ed00",
        "primary": "#8ff5ff",
        "surface-container-highest": "#222531",
        "surface-bright": "#292c38",
        "on-secondary": "#290067",
        "secondary-dim": "#874cff",
        "outline-variant": "#464751",
        "secondary-fixed": "#dac9ff",
        "secondary-fixed-dim": "#ceb9ff",
        "on-tertiary-fixed": "#344900",
        "inverse-on-surface": "#53545e",
        "on-primary-fixed": "#003f43"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Manrope"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
