/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ILandRegistry, ILandRegistryInterface } from "../../LandNFT.sol/ILandRegistry.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "landId",
        "type": "uint256"
      }
    ],
    "name": "getLandDetails",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "landId",
            "type": "uint256"
          },
          {
            "internalType": "string",
            "name": "surveyNumber",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "plotNumber",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "landAddress",
            "type": "string"
          },
          {
            "internalType": "uint256",
            "name": "area",
            "type": "uint256"
          },
          {
            "internalType": "string",
            "name": "titleDeedURI",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "ownershipProofURI",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "geoLocationURI",
            "type": "string"
          },
          {
            "internalType": "address",
            "name": "owner",
            "type": "address"
          },
          {
            "internalType": "bool",
            "name": "verified",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "exists",
            "type": "bool"
          }
        ],
        "internalType": "struct ILandRegistry.Land",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ILandRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): ILandRegistryInterface {
      return new Interface(_abi) as ILandRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ILandRegistry {
      return new Contract(address, _abi, runner) as unknown as ILandRegistry;
    }
  }
  