/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ILandRegistry__factory } from './ILandRegistry__factory.js';
export { LandNFT__factory } from './LandNFT__factory.js';