/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IEscrow {
      
    export type EscrowTxStruct = {escrowId: BigNumberish, tokenId: BigNumberish, buyer: AddressLike, seller: AddressLike, amount: BigNumberish, verified: boolean, completed: boolean, refunded: boolean}

    export type EscrowTxStructOutput = [escrowId: bigint, tokenId: bigint, buyer: string, seller: string, amount: bigint, verified: boolean, completed: boolean, refunded: boolean] & {escrowId: bigint, tokenId: bigint, buyer: string, seller: string, amount: bigint, verified: boolean, completed: boolean, refunded: boolean }
  
    }

  export interface IEscrowInterface extends Interface {
    getFunction(nameOrSignature: "createEscrow" | "getEscrowDetails"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'createEscrow', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getEscrowDetails', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'createEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEscrowDetails', data: BytesLike): Result;
  }

  

  export interface IEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): IEscrow;
    waitForDeployment(): Promise<this>;

    interface: IEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createEscrow: TypedContractMethod<
      [tokenId: BigNumberish, seller: AddressLike, ],
      [bigint],
      'payable'
    >
    

    
    getEscrowDetails: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [IEscrow.EscrowTxStructOutput],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createEscrow'): TypedContractMethod<
      [tokenId: BigNumberish, seller: AddressLike, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'getEscrowDetails'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [IEscrow.EscrowTxStructOutput],
      'view'
    >;

    

    filters: {
      
    };
  }