/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ILandRegistry, ILandRegistryInterface } from "../../Marketplace.sol/ILandRegistry.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "landId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "transferOwnership",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ILandRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): ILandRegistryInterface {
      return new Interface(_abi) as ILandRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ILandRegistry {
      return new Contract(address, _abi, runner) as unknown as ILandRegistry;
    }
  }
  