/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ILandNFT, ILandNFTInterface } from "../../Escrow.sol/ILandNFT.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "ownerOf",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ILandNFT__factory {
    static readonly abi = _abi;
    static createInterface(): ILandNFTInterface {
      return new Interface(_abi) as ILandNFTInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ILandNFT {
      return new Contract(address, _abi, runner) as unknown as ILandNFT;
    }
  }
  