/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ILandRegistry {
      
    export type LandStruct = {landId: BigNumberish, surveyNumber: string, plotNumber: string, landAddress: string, area: BigNumberish, titleDeedURI: string, ownershipProofURI: string, geoLocationURI: string, owner: AddressLike, verified: boolean, exists: boolean}

    export type LandStructOutput = [landId: bigint, surveyNumber: string, plotNumber: string, landAddress: string, area: bigint, titleDeedURI: string, ownershipProofURI: string, geoLocationURI: string, owner: string, verified: boolean, exists: boolean] & {landId: bigint, surveyNumber: string, plotNumber: string, landAddress: string, area: bigint, titleDeedURI: string, ownershipProofURI: string, geoLocationURI: string, owner: string, verified: boolean, exists: boolean }
  
    }

  export interface ILandRegistryInterface extends Interface {
    getFunction(nameOrSignature: "getLandDetails"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getLandDetails', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getLandDetails', data: BytesLike): Result;
  }

  

  export interface ILandRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): ILandRegistry;
    waitForDeployment(): Promise<this>;

    interface: ILandRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getLandDetails: TypedContractMethod<
      [landId: BigNumberish, ],
      [ILandRegistry.LandStructOutput],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getLandDetails'): TypedContractMethod<
      [landId: BigNumberish, ],
      [ILandRegistry.LandStructOutput],
      'view'
    >;

    

    filters: {
      
    };
  }