/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'IEscrow', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEscrow__factory>
getContractFactory(name: 'ILandNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ILandNFT__factory>
getContractFactory(name: 'ILandRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ILandRegistry__factory>
getContractFactory(name: 'Marketplace', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Marketplace__factory>
getContractFactory(name: 'Escrow', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Escrow__factory>
getContractFactory(name: 'ILandNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ILandNFT__factory>
getContractFactory(name: 'LandRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LandRegistry__factory>
getContractFactory(name: 'ILandRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ILandRegistry__factory>
getContractFactory(name: 'LandNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LandNFT__factory>

  getContractAt(name: 'IEscrow', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEscrow>
getContractAt(name: 'ILandNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ILandNFT>
getContractAt(name: 'ILandRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ILandRegistry>
getContractAt(name: 'Marketplace', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Marketplace>
getContractAt(name: 'Escrow', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Escrow>
getContractAt(name: 'ILandNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ILandNFT>
getContractAt(name: 'LandRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LandRegistry>
getContractAt(name: 'ILandRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ILandRegistry>
getContractAt(name: 'LandNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LandNFT>

  deployContract(name: 'IEscrow', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEscrow>
deployContract(name: 'ILandNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILandNFT>
deployContract(name: 'ILandRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILandRegistry>
deployContract(name: 'Marketplace', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Marketplace>
deployContract(name: 'Escrow', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Escrow>
deployContract(name: 'ILandNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILandNFT>
deployContract(name: 'LandRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LandRegistry>
deployContract(name: 'ILandRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILandRegistry>
deployContract(name: 'LandNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LandNFT>

  deployContract(name: 'IEscrow', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEscrow>
deployContract(name: 'ILandNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILandNFT>
deployContract(name: 'ILandRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILandRegistry>
deployContract(name: 'Marketplace', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Marketplace>
deployContract(name: 'Escrow', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Escrow>
deployContract(name: 'ILandNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILandNFT>
deployContract(name: 'LandRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LandRegistry>
deployContract(name: 'ILandRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILandRegistry>
deployContract(name: 'LandNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LandNFT>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  